project/program/urls.py
from django.conf import settings
from django.urls import path

from .views import (
    SpeakersView, PerformersView, SideEventsView,
    PresenterView, ScheduleView,
)


urlpatterns = [
    path('speakers/', SpeakersView.as_view(), name='speakers'),
    path('performers/', PerformersView.as_view(), name='performers'),
    path('side-events/', SideEventsView.as_view(), name='side-events'),
    path('event/', PresenterView.as_view(), name='presenter'),
    path('event/<slug:slug>', PresenterView.as_view(), name='presenter'),
]

if settings.TEDXNTUA_SCHEDULE_ENABLED:
    urlpatterns += [
        path('schedule/', ScheduleView.as_view(), name='schedule'),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import RedirectView
from django.utils.translation import ugettext_lazy as _


urlpatterns = static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('project.home.urls')),
    path('', include('django.conf.urls.i18n')),
    path('', include('project.program.urls')),
    path('partners/', include('project.partners.urls')),
    path('about/', include('project.about.urls')),
)

admin.site.site_header = _('TEDxNTUA <VAR:YEAR> administration')
admin.site.site_title = _('TEDxNTUA <VAR:YEAR> admin')

project/program/models.py
'''
Models for the "Program" section of the website.

The event consists of Activities presented by Presenters, where each activity
happens on one of the two stages: Main event, Side events.

In this module you'll find:
- Django models for each entity.
- Post-save signal receivers that generate thumbnails for each entry's image.
- Helper managers for queries like "get all presenters who are speakers".
- The `get_schedule` method of the ActivityManager. It gets all the activities
  and organizes them by start time and stage in order to produce the schedule
  that will be consumed by the ScheduleView.
'''
from enum import Enum
import logging

from django.core.exceptions import ValidationError
from django.db import models
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.fields import AutoSlugField

from versatileimagefield.fields import VersatileImageField
from versatileimagefield.image_warmer import VersatileImageFieldWarmer
from parler.models import TranslatableModel, TranslatedFields, TranslationDoesNotExist
from parler.managers import TranslatableQuerySet, TranslatableManager
from project.utils.slug import EnglishAutoSlugField


logger = logging.getLogger(__name__)

# Stage non-database model

class Stage(Enum):
    '''Enum class that represents the event stages'''
    MAIN = 'main'
    SIDE = 'side'

    @classmethod
    def get_verbose_names(cls):
        '''The stage labels that will be shown in the schedule page'''
        return {
            cls.MAIN.value: _('MAIN STAGE'),
            cls.SIDE.value: _('SIDE EVENTS'),
        }

    @classmethod
    def from_activity(cls, activity):
        '''Maps an activity to the corresponding stage according to activity type'''
        map_to_stage = {
            Activity.GENERAL: cls.MAIN.value,
            Activity.TALK: cls.MAIN.value,
            Activity.PERFORMANCE: cls.MAIN.value,
            Activity.SIDE_EVENT: cls.SIDE.value,
        }
        # Return None if activity type is not mapped to any stage
        return map_to_stage.get(activity.activity_type, None)


# Activity model & managers

class ActivityManager(TranslatableManager):
    '''
    The main manager of the Activity model providing class-level functionality.
    '''
    def get_schedule(self, unpublished=False):
        '''
        Get the schedule of the event organized by time and stages.

        Generates a dictionary with time (hh:mm format) as keys
        (in ascending order) and the activities starting on each stage at that
        time (or None) as values.

        If two activities start at the same time and stage, only one will be
        returned, since the other will be overridden. This is prevented by the
        clean() method of the Activity model.

        Activities with no start or end time will not be included.

        Example result:
        {
            '11:30': {
                'main': <Activity: Exploring space (Talk)>,
                'side': None
            },
            '12:20': {
                'main': <Activity: Banjo session (Performance)>,
                'side': <Activity: Labyrinth of Senses (Side event)>
            },
            ...
        }

        Parameters
        ----------
        unpublished : bool (default False)
            Controls if unpublished activities are included.
        '''

        slots = {}
        # Initialize each line to contain None for each stage
        blank_line = {stage.value: None for stage in Stage}

        activities = Activity.objects.select_related('presenter').filter(
            start__isnull=False,
            end__isnull=False,
        )
        if not unpublished:
            # Hide activities when their presenter is unpublished
            activities = activities.filter(
                presenter__is_published=True,
                is_published=True,
            )

        for activity in activities:
            # Get time slot
            slot = activity.start_time
            # Get stage name
            stage = Stage.from_activity(activity)
            if stage is None:
                continue

            if slot not in slots:
                # If time slot was unused, declare it
                # and initialize it to empty
                slots[slot] = blank_line.copy()
            # Store activity in time slot and in stage column
            slots[slot][stage] = activity

        # Sort by ascending time
        slots = dict(sorted(slots.items()))
        return slots

    def make_empty(self, **other_values):
        '''
        Generates instance with placeholders for the required fields.

        Other values can also be passed as keyword arguments.
        The instance will not be saved to the database.
        '''
        a = self.model(**other_values)
        for lang in ['el', 'en']:
            a.set_current_language(lang)
            for field in ['title', 'subtitle', 'description']:
                setattr(a, field, '-')
        return a

    def published(self):
        '''
        Fetches only published activities.

        Becomes handy in templates where we can write for example:
        `for act in presenter.activity_set.published`.
        '''
        return self.get_queryset().filter(
            presenter__is_published=True,
            is_published=True,
        )


class ActivityTypeManager(TranslatableManager):
    '''
    Abstract class for managers that return activities of specific type,
    e.g. talks, performances, etc.
    '''
    def __init__(self, type_):
        super().__init__()
        self.type_ = type_

    def get_queryset(self):
        return super().get_queryset().filter(
            activity_type=self.type_,
        )

    def published(self):
        return self.get_queryset().filter(
            presenter__is_published=True,
            is_published=True,
        )


class Activity(TranslatableModel):
    '''
    A thing happening in the event, ie. a talk, a performance, a workshop
    or the hosting of the event.
    '''
    GENERAL = 'G'
    TALK = 'T'
    PERFORMANCE = 'P'
    SIDE_EVENT = 'S'
    HOSTING = 'H'
    TYPE_CHOICES = (
        (GENERAL, _('General')),
        (TALK, _('Talk')),
        (PERFORMANCE, _('Performance')),
        (SIDE_EVENT, _('Side event')),
        (HOSTING, _('Hosting')),
    )

    activity_type = models.CharField(max_length=1, choices=TYPE_CHOICES,
                                     verbose_name='Type')

    start = models.TimeField(null=True, blank=True)
    end = models.TimeField(null=True, blank=True)

    translations = TranslatedFields(
        title=models.CharField(max_length=255),
        subtitle=models.TextField(),
        description=models.TextField(),
    )

    image = VersatileImageField(
        'Image',
        upload_to='activities/',
        width_field='image_width',
        height_field='image_height',
        null=True,
        blank=True,
    )
    image_height = models.PositiveIntegerField(editable=False, null=True)
    image_width = models.PositiveIntegerField(editable=False, null=True)

    is_published = models.BooleanField(_('Published'), default=True)

    presenter = models.ForeignKey(
        'Presenter',
        null=True,
        on_delete=models.SET_NULL,
    )

    objects = ActivityManager()
    talks = ActivityTypeManager(TALK)
    performances = ActivityTypeManager(PERFORMANCE)
    side_events = ActivityTypeManager(SIDE_EVENT)

    def __str__(self):
        return self.title

    @property
    def start_time(self):
        if not self.start:
            return None
        return f'{self.start.hour:02d}:{self.start.minute:02d}'

    @property
    def end_time(self):
        if not self.end:
            return None
        return f'{self.end.hour:02d}:{self.end.minute:02d}'

    @property
    def time_span(self):
        if (not self.start) or (not self.end):
            return None
        return f'{self.start_time}-{self.end_time}'

    def clean(self):
        '''Ensures that only one activity starts at a certain time and stage'''
        # Skip if start time has not been set
        if self.start is None:
            return
        same_time_activities = Activity.objects.filter(start=self.start)
        for other in same_time_activities:
            if (self.id != other.id
                and Stage.from_activity(self) == Stage.from_activity(other)):
                # If it's not the same activity and they're happening at the same stage
                raise ValidationError('There exists another activity that ' \
                                      'starts at the same time and stage')

    class Meta:
        verbose_name_plural = 'Activities'


@receiver(models.signals.post_save, sender=Activity)
def warm_activity_images(sender, instance, **kwargs):
    '''Ensures images are created post-save.

    Image sizes are stored in base.VERSATILEIMAGEFIELD_RENDITION_KEY_SETS.
    Using a thumbnail__AxA rendition key, the image fits in a AxA rectangle by
    maintaining the aspect ratio.

    Documentation link:
    https://django-versatileimagefield.readthedocs.io/en/latest/overview.html#create-images-wherever-you-need-them
    '''
    if instance.image:
        img_warmer = VersatileImageFieldWarmer(
            instance_or_queryset=instance,
            rendition_key_set='Sizes',
            image_attr='image',
            verbose=True
        )

        img_warmer.warm()
    else:
        logger.info('No image file added for this activity: %s', instance)


# Presenter model & managers

class PresenterTypeManager(TranslatableManager):
    '''
    Abstract class for managers that return presenters of specific activity
    types, e.g. speakers, performers, etc.
    '''
    def __init__(self, type_):
        super().__init__()
        self.type_ = type_

    def get_queryset(self):
        return super().get_queryset().filter(
            activity__activity_type=self.type_,
        ).distinct()

project/program/forms/activity_form.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from parler.admin import TranslatableModelForm

from ..models import Activity


class ActivityModelForm(TranslatableModelForm):
    '''
    Custom admin form for Activities.

    Adds the option to get activity image from presenter and sets field order.
    '''

    get_image_from_presenter = forms.BooleanField(
        required=False,
        label=_('Get image from presenter'),
        help_text=_('If selected, the image will be overridden by that of the presenter'),
    )

    class Meta:
        model = Activity
        fields = (
            'activity_type',
            'is_published',
            'start',
            'end',
            'image',
            'get_image_from_presenter',
            'presenter',
            'title',
            'subtitle',
            'description',
        )

    def save(self, commit=True):
        '''
        Handles form save and get_image_from_presenter toggle.

        Useful links:
        https://docs.djangoproject.com/en/<VAR:DJANGO_VERSION>/topics/forms/modelforms/#the-save-method
        https://stackoverflow.com/a/817364/11114199
        '''
        obj = super().save(commit=False)

        get_im = self.cleaned_data.get('get_image_from_presenter', False)
        presenter = self.cleaned_data.get('presenter', None)
        if get_im and presenter:
            # Set image field to point to presenter's image
            if presenter.image:
                obj.image.name = presenter.image.name

        if commit:
            obj.save()

        return obj

project/program/forms/presenter_form.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from parler.admin import TranslatableModelForm

from ..models import Activity, Presenter


CREATE_ACTIVITY_CHOICES = (
    ('', _('No')), # Add No as option
) + Activity.TYPE_CHOICES

class PresenterModelForm(TranslatableModelForm):
    '''
    Custom admin form for Presenters.

    Adds the option to create empty unpublished activity of given type.
    '''

    create_empty_activity = forms.ChoiceField(
        required=False,
        label=_('Assign empty activity'),
        help_text=_('This will create an empty and unpublished '
                    'activity of the given type with the same '
                    'photo as the presenter\'s'),
        choices=CREATE_ACTIVITY_CHOICES,
    )

    class Meta:
        model = Presenter
        fields = (
            'name',
            'occupation',
            'short_bio',
            'quote',
            'image',
            'link',
            'create_empty_activity',
            'is_published',
        )

project/program/views.py
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from .models import Presenter, Activity, Stage
from project.utils.url import is_url_same_domain


class SpeakersView(View):
    template_name = 'program/listing.html'

    def get(self, request):
        if settings.TEDXNTUA_SHOW_UNPUBLISHED:
            items = Presenter.speakers.all()
        else:
            items = Presenter.speakers.published()

        return render(request, self.template_name, {
            'listing_type': 'speakers',
            'items': items,
            'placeholders': list(range(4)),
        })

class PerformersView(View):
    template_name = 'program/listing.html'

    def get(self, request):
        if settings.TEDXNTUA_SHOW_UNPUBLISHED:
            items = Presenter.performers.all()
        else:
            items = Presenter.performers.published()

        return render(request, self.template_name, {
            'listing_type': 'performers',
            'items': items,
            'placeholders': list(range(4)),
        })

class SideEventsView(View):
    template_name = 'program/listing.html'

    def get(self, request):
        # Side events view is special in that the listing shows the *activities*
        # instead of their presenters
        if settings.TEDXNTUA_SHOW_UNPUBLISHED:
            items = Activity.side_events.select_related('presenter')
        else:
            items = Activity.side_events.published().select_related('presenter')

        return render(request, self.template_name, {
            'listing_type': 'side_events',
            'items': items,
            'placeholders': list(range(4)),
        })


class PresenterView(View):
    template_name = 'program/presenter.html'

    def get(self, request, slug=None):
        if slug is None:
            return redirect('index')

        # Add link to previous page if it was on the same domain
        go_back_url = request.META.get('HTTP_REFERER')
        if not is_url_same_domain(request, go_back_url):
            go_back_url = ''

        if settings.TEDXNTUA_SHOW_UNPUBLISHED:
            presenter = get_object_or_404(Presenter, slug=slug)
            activities = presenter.activity_set.all()
        else:
            presenter = get_object_or_404(Presenter, slug=slug,
                    is_published=True)
            activities = presenter.activity_set.published()

        return render(request, self.template_name, {
            'presenter': presenter,
            'activities': activities,
            'go_back_url': go_back_url,
        })

class ScheduleView(View):
    template_name = 'program/schedule.html'

    def get(self, request):
        schedule = Activity.objects.get_schedule(
            unpublished=settings.TEDXNTUA_SHOW_UNPUBLISHED,
        )
        stages = Stage.get_verbose_names()
        return render(request, self.template_name, {
            'schedule': schedule,
            'stages': stages,
        })

project/program/templates/program/_event-tabs.html
{% load i18n %}
{% with url_name=request.resolver_match.url_name %}
<ul class="nav nav-scrollable-tabs">
    <li class="nav-item">
        <a href="{% url 'speakers' %}" class="btn {% if url_name == 'speakers' %}btn-secondary{% else %}btn-white{% endif %}">{% trans 'Speakers' %}</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'performers' %}" class="btn {% if url_name == 'performers' %}btn-secondary{% else %}btn-white{% endif %}">{% trans 'Performers' %}</a>
    </li>
    <li class="nav-item">
        <a href="{% url 'side-events' %}" class="btn {% if url_name == 'side-events' %}btn-secondary{% else %}btn-white{% endif %}">{% trans 'Side events' %}</a>
    </li>
    {% if settings.TEDXNTUA_SCHEDULE_ENABLED %}
    <li class="nav-item">
        <a href="{% url 'schedule' %}" class="btn {% if url_name == 'schedule' %}btn-secondary{% else %}btn-white{% endif %}">{% trans 'Schedule' %}</a>
    </li>
    {% endif %}
</ul>
{% endwith %}

project/program/templates/program/listing.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% spaceless %}
    {% if listing_type == 'speakers' %}
        {% trans 'Speakers' %}
    {% elif listing_type == 'performers' %}
        {% trans 'Performers' %}
    {% elif listing_type == 'side_events' %}
        {% trans 'Side events' %}
    {% endif %}
{% endspaceless %}{% endblock %}
{% block description %}{% spaceless %}
    {% if listing_type == 'speakers' %}
        {% trans 'speakers.description' %}
    {% elif listing_type == 'performers' %}
        {% trans 'performers.description' %}
    {% elif listing_type == 'side_events' %}
        {% trans 'side_events.description' %}
    {% endif %}
{% endspaceless %}{% endblock %}
{% block content %}
<article class="event-page listing-page {{ listing_type }}-page">
    {% include "program/_event-tabs.html" %}
    <div class="container-fluid listing-grid">
        {% for item in items %}
            {% if listing_type == "side_events" %}
                {% comment %}
                    For side events, link to the presenter
                {% endcomment %}
            <a class="col col-6 col-md-4 col-lg-3 col-xl-2 underline-parent"
                    href="{% url "presenter" slug=item.presenter.slug %}">
            {% else %}
            <a class="col col-6 col-md-4 col-lg-3 col-xl-2 underline-parent"
                    href="{% url "presenter" slug=item.slug %}">
            {% endif %}
                {% if item.image %}
                    <img class="image"
                        srcset="{{ item.image.thumbnail.320x320.url }} 320w,
                            {{ item.image.thumbnail.720x720.url }} 720w,
                            {{ item.image.thumbnail.1024x1024.url }} 1024w"
                        sizes="(max-width: 576px) 320px,
                            (max-width: 992px) 720px,
                            1024px"
                        src="{{ item.image.thumbnail.320x320.url }}"
                        alt="" />
                {% else %}
                    <div class="image image-placeholder squares-overlayed blue-black"
                        aria-hidden="true"></div>
                {% endif %}
                {% if listing_type == "side_events" %}
                    <h5 class="underline-hover">{{ item.title }}</h5>
                    <h6>{{ item.subtitle }}</h6>
                {% else %}
                    <h5 class="underline-hover">{{ item.name }}</h5>
                    <h6>{{ item.occupation }}</h6>
                {% endif %}
            </a>
        {% endfor %}
        {% for p in placeholders reversed %}
            {% if items|length <= p %}
                <a class="col col-6 col-md-4 col-lg-3 col-xl-2">
                    <div class="placeholder">
                        <div class="image {% if p|divisibleby:"2" %}woman{% else %}man{% endif %}-icon"
                            aria-hidden="true"></div>
                        <h5>{% trans 'more_soon' %}</h5>
                    </div>
                </a>
            {% endif %}
        {% endfor %}
    </div>
</article>
{% endblock %}

project/program/templates/program/presenter.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{{ presenter.name }}{% endblock %}
{% block description %}{{ presenter.name }}: {{ presenter.occupation }}{% endblock %}
{% block content %}
<article class="presenter-page">
    {% if go_back_url %}
        <a href="{{ go_back_url }}" class="btn btn-secondary">
            &lt; {% trans 'back' %}
        </a>
    {% endif %}
    <div class="presenter">
        {% if presenter.image %}
            <img class="image"
                srcset="{{ presenter.image.thumbnail.320x320.url }} 320w,
                        {{ presenter.image.thumbnail.720x720.url }} 720w,
                        {{ presenter.image.thumbnail.1024x1024.url }} 1024w"
                sizes="(max-width: 576px) 320px,
                        (max-width: 992px) 720px,
                        1024px"
                src="{{ presenter.image.thumbnail.320x320.url }}"
                alt="" />
        {% else %}
            <div class="image image-placeholder" aria-hidden="true">
                <div class="squares-overlayed blue-black"></div>
            </div>
        {% endif %}
        <div class="info">
            <h1>{{presenter.name}}</h1>
            <h2>{{presenter.occupation}}</h2>
            <div class="collapse content" id="description">
                {{presenter.short_bio|safe}}
            </div>
            <a href="#description" class="btn btn-primary" data-toggle="collapse"
                aria-expanded="false" aria-controls="description">
                {% trans 'presenter.read_full' %}
            </a>
        </div>
    </div>
    <div class="activities">
        {% for activity in activities %}
        <div class="activity">
            <header>
                <h5>{{ activity.title }}</h5>
                <h6 class="h5">
                    <span class="type">
                        {{activity.get_activity_type_display | upper}}
                    </span>
                    {% if activity.start and activity.end %}
                        <span class="sep">|</span>
                        <time>{{activity.start_time}}</time>&mdash;<time>{{activity.end_time}}</time>
                    {% endif %}
                </h6>
            </header>
            <div class="content">
                {{activity.description|safe}}
            </div>
        </div>
        {% endfor %}
    </div>
</article>
{% endblock %}

project/program/templates/program/schedule.html
{% extends "base.html" %}
{% load i18n %}
{% load render_bundle from webpack_loader %}
{% block title %}{% trans 'schedule.title' %}{% endblock %}
{% block description %}{% trans 'schedule.description' %}{% endblock %}
{% block content %}
<article class="event-page schedule-page">
    {% include "program/_event-tabs.html" %}
    <div id="schedule-table" role="table" data-activetab="main">
        <div role="rowgroup" class="table-heading">
            <div role="row">
                <span role="columnheader">{% trans 'TIME' %}</span>
                {% for id, stage in stages.items %}
                <span role="columnheader" class="d-none d-lg-inline">{{ stage }}</span>
                {% endfor %}
                <form role="columnheader" class="d-lg-none">
                    <select id="stage-selector" aria-label="Filter by event stage" class="form-control">
                        {% for id, stage in stages.items %}
                        <option{% if forloop.first %} selected{% endif %} value="{{ id }}">{{ stage }}</option>
                        {% endfor %}
                    </select>
                </form>
            </div>
        </div>
        <div role="rowgroup">
            {% for time, row in schedule.items %}
            <div role="row" class="{% if not row.main %}hide-main {% endif %}{% if not row.side %}hide-side {% endif %}">
                <span role="cell" class="time">{{ time }}</span>
                {% for stage, event in row.items %}
                <span role="cell">
                    {% if event %}
                    <a class="cell-content" href="{% url "presenter" slug=event.presenter.slug %}">
                        {% if event.image %}
                        <img class="image"
                             srcset="{{ event.image.thumbnail.320x320.url }} 320w,
                                     {{ event.image.thumbnail.720x720.url }} 720w,
                                     {{ event.image.thumbnail.1024x1024.url }} 1024w"
                            sizes="(max-width: 576px) 320px,
                                   (max-width: 992px) 720px,
                                   1024px"
                            src="{{ event.image.thumbnail.320x320.url }}"
                            alt="" />
                        {% else %}
                        <div class="image placeholder squares-overlayed blue-black"
                             aria-hidden="true"></div>
                        {% endif %}
                        <div class="info">
                            <h5>{{ event.title }}</h5>
                            <p>{{ event.subtitle }}</p>
                        </div>
                        <div class="chevron-container">
                            <div class="chevron-right"></div>
                        </div>
                    </a>
                    {% else %}
                    <div class="cell-content"></div>
                    {% endif %}
                </span>
                {% endfor %}
            </div>
            {% endfor %}
        </div>
    </div>
</article>
{% endblock %}
{% block scripts %}
    {% render_bundle 'schedule' 'js' %}
{% endblock %}

project/program/templates/program/speakers.html
{% extends "base.html" %}
{% block title %}Speakers{% endblock %}
{% block content %}
<article id="speakers">

<ul class="list">
    {% for speaker in speakers %}
    <li>
         {{ speaker.name }}
         <p>{{ speaker.short_bio }}</p>
    </li>
    {% endfor %}
</ul>
</article>
{% endblock %}